version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5433:5432" # Map host port 5433 to container port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist data

volumes:
  pgdata:
