services:
  # Next.js app
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://valkey:6379
      - PORT=3000
      - HOSTNAME=0.0.0.0
    depends_on:
      valkey:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Valkey server (Redis-compatible)
  valkey:
    image: valkey/valkey:alpine
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  valkey-data:
