version: '3.8'

services:
  test-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Add initialization scripts
      - ./docker/init-scripts:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "shared_preload_libraries=uuid-ossp"]

volumes:
  pgdata: 