name: Copilot Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  copilot-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Copilot Code Review
        run: |
          npx @github/copilot-cli code-review --repo ${{ github.repository }} --pull-request ${{ github.event.pull_request.number }}