name: Vitest Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Vitest Tests
    runs-on: ubuntu-latest
    
    # Add this services block to run PostgreSQL
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci

      - name: Run Prisma migrations
        run: npx prisma migrate deploy
        env:
          NEXT_PUBLIC_DATABASE_URL: "postgresql://user:password@localhost:5432/testdb"

      - name: Run Vitest tests
        run: npm test
        id: vitest
        env:
          NEXT_PUBLIC_DATABASE_URL: "postgresql://user:password@localhost:5432/testdb"

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: coverage/
          retention-days: 7 